# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db8b2a55df5526caffc1c83a3c890ab86eaa9e41520fa36098131564bcd76242f92aec725f56f95d1ac5f3ac60b58816aede1ad724e1e9c2ea096453cc329b6f

test:
  secret_key_base: fff9ec092d240c4ec9e4aee2a106f3cf2e235ad746294acdd85dfd540c4026c98baa8110c8ca9aa2b9f9d739465e1519846bb4880892499664b6dc3a332578ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
